### ISSUE TITLE
cc-snapshot (doubt, issues)

### ISSUE THREAD

**Issue by arundasan91** [badock/ChameleonSnapshotting#1]
Hello,

I was wondering why repeated checks is required in the [cc-snapshot file, line 143 to 150](https://github.com/ChameleonCloud/cc-snapshot/blob/master/cc-snapshot#L143-L150). For instances with around 15GB to 20GB of used space, this leads to a few hours of snapshot process.

Yes, container sizes should not be that big. I truly understand that we should clean the server, upload stuff to swift to free up even more space and just keep the necessary before snapshotting process. However, that might not work always, for example in a node with a lot of NVIDIA, CUDA drivers, various deep learning frameworks, docker containers and such. 

Still, checking for a fail 5 different times, even for smaller snapshot sizes, is a bit too much in my opinion. Did you guys do it in purpose to clean a prior bug ? If not, I truly believe taking it off would make life much easier. The snapshotting process takes way too long now !

```
# The following code is inspired from http://unix.stackexchange.com/questions/82598
n=0
until [ $n -ge 5 ]
do
   tar cf /tmp/snapshot.tar / --selinux --acls $TAR_ARGS --numeric-owner --one-file-system  --exclude=/tmp/snapshot.tar --exclude=/tmp/* --exclude=/proc/* --exclude=/var/tmp/* --exclude=/boot/extlinux && break
   n=$[$n+1]
   sleep 15
done
```

Also, the openrc file creation process does not work sometimes. After creating the compressed qcow2 images, an error message usually returns stating that there should be proper authentication required. I verified it in two different ways:
1. Went to `/tmp` folder and sourced the `openrc` file generated (while running cc-snapshot) with my credentials.
     -Tried `glance image-list` and it returned an authentication error.
2. Downloaded openrc from dashboard (Access and Security) and sourced it in the same session.
     -Tried `glance image-list` and it went fine.

I later used `glance image-create --name 'SNAPSHOT_NAME' --disk-format qcow2 --container-format bare < /tmp/snapshot_compressed.qcow2` this command to upload the compressed qcow2 file as a glance image.

Please look into this. I've been helping my colleagues with image snapshots for a long time now since cc-snapshot fails regularly. That said, I was able to create an image based on a GPU instance using cc-snapshot a week ago but had to reinstall NVIDIA drivers and some other libraries after spinning an instance based on the image created.

**Comment by priteau** [comment]
Hello,

The retry block is designed to catch tar execution failures, but I agree that a better solution should be available. I am not able to reproduce these errors myself, would you be willing to share an image that triggers them with us? You can do so via the Chameleon help desk.

As for the authentication errors, are you using the latest version of cc-snapshot? It would be helpful to see the content of the generated `openrc` file, can you share it with us? (preferably via the help desk)

**Comment by arundasan91** [comment]
Thanks a lot. I will do the same. 

I am using the latest master.
