### ISSUE TITLE
Fail-fast on wrong credentials

### ISSUE THREAD

**Issue by nicktimko** [badock/ChameleonSnapshotting#2]
If the user enters the wrong credentials at the start, they get to wait through the creation of their image, then see it fail after everything else worked. Adding a check like

```
if ! glance image-list --limit 1; then 
    echo 'Invalid credentials'
    exit
fi
```

Would abort quickly, so the user could re-run the script and get re-prompted.

**Comment by priteau** [comment]
This was implemented in 951aa4d16446b8b2dd723c5d3e1620aec1dfa27a.
