### ISSUE TITLE
Manually exclude folders from CLI

### ISSUE THREAD

**Issue by arundasan91** [badock/ChameleonSnapshotting#3]
Hello,

It would be awesome if users could manually exclude folders to be snapshotted. 

**Use Case:**
My Machine Learning pipeline usually involves storing large datasets in local storage and on Swift. The training scripts and other notebooks are of very little size. Now, I have to back-up my data in local storage to Swift and then remove it (from local) before beginning the snapshotting procedure.

**Request:**
A way to exclude folders from CLI, say for example:
```
sudo cc-snapshot [snapshot_name] --exclude /home/cc/datasets --exclude /home/cc/trained_models
```
**Possible Edit:**
https://github.com/ChameleonCloud/cc-snapshot/blob/master/cc-snapshot#L147

Will Chameleon accept a PR? I can work on it on my free time.

Thanks!

**Comment by priteau** [comment]
Hello Arun,

Thanks for sharing your feature request. I think it would be good to have.
If you're able to implement it, the Chameleon project would love to receive your pull request. Thanks!

**Comment by arundasan91** [comment]
Thank you. I will implement the same and update.

**Comment by arundasan91** [comment]
Hello @priteau ,

Please find the[PR#4](https://github.com/ChameleonCloud/cc-snapshot/pull/4) regarding the same issue. I've tested the scripts with every option I could.

Thanks

**Comment by priteau** [comment]
Closing as the pull request was merged.
